# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = 'vagrant-nginx'.freeze

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = VM_NAME

  config.vm.provider 'virtualbox' do |vb|
    vb.name = VM_NAME
    vb.memory = 2048
  end

  config.vm.network 'private_network', ip: '192.168.50.10'

  config.vm.provision :shell, path: '.provision/bootstrap.sh'
end
