- name: Install docker and its dependencies
  import_playbook: common/docker-setup-playbook.yml

- name: Disable swap to allow kubelet to start
  import_playbook: common/disable-swap-playbook.yml

- name: Install kubelet, kubeadm and kubectl
  import_playbook: common/kubernetes-install-playbook.yml

- name: Join the kubernetes cluster
  import_playbook: node/join-cluster-playbook.yml
