---
- hosts: all
  become: true
  tasks:
    - name: Setup kubeconfig for vagrant user. Create directory
      file:
        path: /home/vagrant/.kube
        state: directory

    # sudo here as become alters privilege on remote and i don't want to alter permissions of system files
    - name: Copy kubeconfig into new directory
      command: sudo cp /etc/kubernetes/admin.conf /home/vagrant/.kube/config

    - name: Change kubeconfig file permissions
      file:
        path: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
