---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - nodejs

  tasks:
    - name: Ensure NodeJS app folder exists.
      file:
        path: "{{ node_apps_location }}"
        state: directory

    - name: Clone project to server.
      git:
        repo: "{{ project_repo }}"
        dest: "{{ node_apps_location }}"
        clone: true
        version: master

    - name: Install app dependencies.
      npm:
        path: "{{ node_apps_location }}"

    - include_role:
        name: mongodb

    - name: Check list of running NodeJS apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start the example app.
      command: "forever start {{ project_location }}/{{ project_app_file }}"
      when: "forever_list.stdout.find(project_location + '/' + project_app_file) == -1"
